practical.practical_type.*:
  type: config_entity
  label: 'Practical Type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    uuid:
      type: stype
      label: 'UUID'
    label:
      type: label
      label: 'Label'
